name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none

schedules:
- cron: "30 17 * * Thu" #UTC Time
  displayName: Weekly Windows Desktop 11 build
  branches:
    include:
    - main
  always: true

pool: automation

variables:
  - group: "vcenter"
  - group: "packer_auto_variables"
  - group: "pkr_svc_acc"
  - group: "windows_desktop_11"
  - group: "ssh_details"

stages:
  - template: templates/prepare_environment.yml
    parameters:
      os_family:                    $(os_family)
      os_flavor:                    $(os_flavor)
      os_version:                   $(os_version)
      guest_os_type:                $(guest_os_type)
      build_directory:              $(build_directory)
      vsphere_server:               $(vsphere_server)
      vsphere_username:             $(svc_username)
      vsphere_password:             $(svc_password)
      winrm_connection_username:    $(winrm_connection_username)
      winrm_connection_password:    $(winrm_connection_password)
      vsphere_datacenter:             $(vsphere_datacenter)
      vsphere_cluster:                $(vsphere_cluster)
      vsphere_datastore:              $(vsphere_datastore)
      vsphere_folder:                 $(vsphere_folder)
      vsphere_library:                $(vsphere_library)
      
  - template: templates/build_image.yml
    parameters:
      os_family:                    $(os_family)
      os_flavor:                    $(os_flavor)
      os_version:                   $(os_version)
      guest_os_type:                $(guest_os_type)
      vsphere_server:               $(vsphere_server)
      vsphere_username:             $(svc_username)
      vsphere_password:             $(svc_password)
      winrm_connection_username:    $(winrm_connection_username)
      winrm_connection_password:    $(winrm_connection_password)
      vsphere_datacenter:             $(vsphere_datacenter)
      vsphere_cluster:                $(vsphere_cluster)
      vsphere_datastore:              $(vsphere_datastore)
      vsphere_folder:                 $(vsphere_folder)
      vsphere_library:                $(vsphere_library)